#pragma once

using namespace ATL;

template <class T>
class CProxy_ICOMManagedTestEvents : public IConnectionPointImpl<T, &__uuidof( _ICOMManagedTestEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
